language: java
jdk:
- oraclejdk8
install:   
- mkdir travis-phantomjs   
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2   
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs   
- export PATH=$PWD/travis-phantomjs:$PATH
script:
- chmod +x ./gradlew
after_success:
- 'if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then exit; fi'
- 'if [ ${TRAVIS_BRANCH} != "master" ]; then exit; fi'
- 'CURRENT_TAG=$(phantomjs gettag.js)'
- 'BUILD_NUMBER=$((CURRENT_TAG+1))'
- 'curl -v -X POST -d "{\"tag\": \"${BUILD_NUMBER}\",\"message\": \"MinigameCore Build ${BUILD_NUMBER}\",\"object\": \"${TRAVIS_COMMIT}\",\"type\": \"commit\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/tags"'
- 'curl -v -X POST -d "{\"ref\": \"refs/tags/${BUILD_NUMBER}\",\"sha\": \"${TRAVIS_COMMIT}\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/refs"'
